---
title: "Data Generation"
author: "Pedro Victor Brasil Ribeiro"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
source('https://raw.githubusercontent.com/ribeiropvb/Util/main/install_packages_if_not_exist.R')

packages <- c('tidyverse', 'mirt')
install_packages_if_not_exist(packages)
pacman::p_load(tidyverse, mirt)

knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

# Data Simulation Method

```{r}
root_path = 'C:/Users/pedro.ribeiro/Desktop/Pedro/MOVE/tcc/data_generation_with_tri/tri_project/'
set.seed(20230202)
df <- read_csv(paste0(root_path,"Data/irt.csv"), col_types = cols(...1 = col_skip()))
df
```

## IRT Modelo

```{r}
# TRI model - graded response model (Samejima, 1969)
# Samejima, F. (1969). Estimation of latent ability using a response pattern of graded scores.
# Psychometrika Monographs, 34.
model_grm <- mirt(df, itemtype = 'graded')

# Estimate the model parameters
fit_grm <- fscores(model_grm)

# Display the estimated item parameters (discrimination and thresholds)
item_parameters <- coef(model_grm)
```

### Parameters

```{r}
for (i in 1:(length(item_parameters)-1)) {
  cat("Item", i, ":\n")
  cat("Discrimination (a):", item_parameters[[i]][1,'a1'], "\n")
  cat("Thresholds (b1, b2, b3, ...):", item_parameters[[i]][1, -1], "\n")
  cat("\n")
}
```

#### Discriminant

```{r}
sapply(item_parameters, function(x) x[1]) %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  magrittr::set_colnames(c('question', 'discrimination_parameter'))
```

### Plots

```{r}
# You can also make item response predictions using the fitted model if needed
plot(model_grm)
```

```{r}
plot(model_grm, type = 'trace')
```

```{r}
plot(model_grm, type = 'itemscore')
```

# Data Generation
## GANs Model

Data generated with Generative Adversarial Network (GAN)

```{r}
new_irt <- read_csv(paste0(root_path, "Data/new_irt_gan.csv"))
```

```{r}
fields::stats(new_irt) %>% t()
```

```{r}
model_grm <- mirt(df, itemtype = 'graded')
fit_grm <- fscores(model_grm)
item_parameters <- coef(model_grm)
```

```{r}
for (i in 1:(length(item_parameters)-1)) {
  cat("Item", i, ":\n")
  cat("Discrimination (a):", item_parameters[[i]][1,'a1'], "\n")
  cat("Thresholds (b1, b2, b3, ...):", item_parameters[[i]][1, -1], "\n")
  cat("\n")
}
```

```{r}
plot(model_grm)
```

```{r}
plot(model_grm, type = 'trace')
```

```{r}
plot(model_grm, type = 'itemscore')
```

## Bootstrap

```{r}
# Load the necessary libraries
library(boot)
```


```{r}
# Create an empty list to store augmented datasets
augmented_datasets <- list()

# Number of bootstrap samples
num_bootstrap_samples <- 1000

# Perform bootstrap data augmentation
for (i in 1:num_bootstrap_samples) {
  # Generate a bootstrap sample by resampling with replacement
  bootstrap_indices <- sample(1:nrow(df), replace = TRUE)
  bootstrap_sample <- df[bootstrap_indices, ]
  
  # Store the bootstrap sample in the list of augmented datasets
  augmented_datasets[[i]] <- bootstrap_sample
}
```

```{r}
# Access one of the augmented datasets (for example, the first one)
first_augmented_dataset <- do.call(rbind, augmented_datasets)
rownames(first_augmented_dataset) <- NULL
first_augmented_dataset[1:num_bootstrap_samples,] %>% 
  write.csv(paste0(root_path,"Data/new_irt_boot.csv"))
```

```{r}
model_boot_grm <- mirt(first_augmented_dataset, itemtype = 'graded')

# Estimate the model parameters
fit_boot_grm <- fscores(model_boot_grm)

# Display the estimated item parameters (discrimination and thresholds)
item_parameters <- coef(model_boot_grm)
for (i in 1:(length(item_parameters)-1)) {
  cat("Item", i, ":\n")
  cat("Discrimination (a):", item_parameters[[i]][1,'a1'], "\n")
  cat("Thresholds (b1, b2, b3, ...):", item_parameters[[i]][1, -1], "\n")
  cat("\n")
}
```

```{r}
plot(model_boot_grm)
```

```{r}
plot(model_boot_grm, type = 'trace')
```

```{r}
plot(model_boot_grm, type = 'itemscore')
```













































